Initial progress to get skyimager and skybian to include hypervisor.

diff --git a/static/skywire-startup b/static/skywire-startup
--- a/static/skywire-startup
+++ b/static/skywire-startup
@@ -7,26 +7,28 @@
 # - Values of the boot params.
 
 DEV_FILE=/dev/mmcblk0
-VISOR_CONF=/etc/skywire/visor-config.json # Location for skywire visor conf.
+VISOR_CONF=/etc/skywire-visor.json
+HYPERVISOR_CONF=/etc/skywire-hypervisor.json
 NET_NAME="skynet"
 
-
-# 'extract_boot_params' extracts boot parameters.
+# 'setup_skywire' extracts boot parameters.
 # These parameters are stored in the MBR (Master Boot Record) Bootstrap code
 # area of the boot device. This starts at position +0E0(hex) and has 216 bytes.
-function extract_boot_params() {
-  if ! readonly BOOT_PARAMS=$(/usr/bin/skywire/read-boot-params -if=$DEV_FILE); then
-    echo "Failed to read boot params."
+function setup_skywire() {
+  if ! readonly BOOT_PARAMS=$(/usr/bin/skyconf -if=$DEV_FILE); then
+    echo "Failed to setup skywire environment."
     return 1
   fi
   eval "$BOOT_PARAMS"
-  readonly IP GW SK HVS
-  echo "IP=$IP"
-  echo "GW=$GW"
-  echo "SK=$SK"
-  echo "HVS=$HVS"
+  readonly MD IP GW PK SK HVS SS
+  echo "Skywire Startup Mode: MD=$MD"
+  echo "Local IP: IP=$IP"
+  echo "Local Gateway IP: GW=$GW"
+  echo "Local Public Key: PK=$PK"
+  echo "Local Secret Key: SK=$SK"
+  echo "Trusted Hypervisors: HVS=$HVS"
+  echo "Skysocks Passcode: SS=$SS"
 }
-
 
 # 'setup_network' sets up networking for Skybian.
 # It uses the IP (local IP address) and GW (Gateway IP address) of the boot
@@ -35,16 +37,16 @@ function extract_boot_params() {
 function setup_network() {
   # If IP and GW are both empty, do nothing.
   if [[ -z "$IP" && -z "$GW" ]]; then
-    echo "ENVs (IP, GW) are both empty, skipping network setup."
+    echo "ENVs (IP, GW) are both empty, skipping network setup_skywire."
     return 0
   fi
 
-  # If network is already setup, do nothing.
+  # If network is already setup_skywire, do nothing.
   CURRENT_IP=$(nmcli c show "$NET_NAME" | grep IP4.ADDRESS | awk '{print $2}' | xargs)
   echo "Current IP address for connection $NET_NAME: $CURRENT_IP"
 
   if [[ "$CURRENT_IP" == "$IP/24" ]]; then
-    echo "Connection $NET_NAME already set, skipping network setup."
+    echo "Connection $NET_NAME already set, skipping network setup_skywire."
     return 0
   fi
 
@@ -63,75 +65,18 @@ function setup_network() {
   nmcli con mod "$NET_NAME" ipv4.dns "1.0.0.1, 1.1.1.1"
 }
 
-
-# 'prepare_mod_settings' prepares the environment for skywire config
-# modification using jq.
-function prepare_mod_settings() {
-  echo "Preparing tools to mod config..."
-  if ! TEMP_FILE=$(mktemp) ; then
-    echo "Failed to create temp dir."
-    exit 1
-  fi
-  if ! JQ=$(command -v jq) ; then
-    echo "Cannot find 'jq', aborting."
-    exit 1
-  fi
-  echo "TEMP_FILE=${TEMP_FILE}"
-  echo "JQ=${JQ}"
-}
-
-
-# 'jq_cfg' is a convenience function for modifying the config file with jq.
-function jq_cfg() {
-    echo "jq_cfg() $*"
-    # shellcheck disable=SC2048 disable=SC2086
-    $JQ $* "${VISOR_CONF}" > "${TEMP_FILE}" && mv "${TEMP_FILE}" "${VISOR_CONF}"
-}
-
-
-# 'set_hypervisors' sets the trusted hypervisor public keys in config.
-# These values are extracted from the HVS boot parameter.
-function set_hypervisors() {
-	if [[ -n ${HVS} ]] ; then
-		# shellcheck disable=SC2016
-		for PK in "${HVS[@]}" ; do jq_cfg --arg pk "${PK}" '.hypervisors+=[$pk]' ; done
-		jq_cfg '.hypervisors|=unique' # ensure PKs are all unique
-	fi
-}
-
 # This is where the magic happens.
+setup_skywire || exit 1
+setup_network || exit 1
+case $MD in
+  "VISOR")
+    echo "Starting 'skywire-visor'..."
+    /usr/bin/skywire-visor "$VISOR_CONF" & ;;
 
-# We can only setup the network if we can obtain boot parameters.
-extract_boot_params && setup_network
+  "HYPERVISOR")
+    echo "Starting 'skywire-hypervisor'..."
+    /usr/bin/skywire-hypervisor "$HYPERVISOR_CONF" & ;;
 
-# If this fails, exit.
-if ! prepare_mod_settings; then
-  echo "Failed to prepare config-mod settings."
-  exit 1
-fi
-
-# Only generate config if not exist.
-if [[ ! -f "${VISOR_CONF}" ]] ; then
-  echo "Skywire config file does not yet exist in ${VISOR_CONF}."
-
-  echo "Generating base config in '${VISOR_CONF}'..."
-  /usr/bin/skywire-cli visor gen-config --output="${VISOR_CONF}" --type="LOCAL" --secret-key="$SK" || exit 1
-
-  echo "Modifying config..."
-	jq_cfg '.transport.log_store.location="/var/log/skywire/transport"'
-	jq_cfg '.dmsg_pty.authorization_file="/var/skywire/dsmgpty/whitelist.json"'
-	jq_cfg '.dmsg_pty.cli_address="/run/skywire/dmsgpty.sock"'
-	jq_cfg '.app_server_sock_file="/run/skywire/appsrv.sock"'
-	jq_cfg '.local_path="/var/skywire/local"'
-	jq_cfg '.apps_path="/usr/bin/skywire/apps"'
-fi
-
-# Anyways ensure hypervisors are set.
-# Otherwise, we will lose control over our visor.
-#set_hypervisors #TODO(evanlinjin): Reenable this once we update skywire to latest.
-
-# Clean up.
-rm -rf "${TEMP_FILE}"
-
-echo "Starting skywire..."
-/usr/bin/skywire/skywire-visor "$VISOR_CONF" &
+  *)
+    exit 1
+esac
